### PR TITLE
Added Mangapanda parser

### PR DESCRIPTION
**Pull request by Evolution0**
Tests included with the author search test removed for obvious reasons (Mangapanda doesn't have such a feature) All passing.

The `_chapter_prev_next()` function is a bit ugly by necessity (Or I'm just being weird) Mangapanda for some insane reason creates a next page link in its nav even if one does not exist, and there is no way to really check without fetching the next page and checking before setting the next page url.

If there is another way to work around this without requesting each next chapter I'm all ears.

### CODE REVIEW

**Comment by Evolution0** [comment]
P.S The check failing is due to a test failing, Mangapanda uses different CDNs and shuffles the image links around a bit, this changes the first few characters of the urls. I'm not sure how to make the expected data check flexible enough to handle that.

To verify that the checks do indeed pass see the previous commit.

**Comment by nhanb** [comment]
Hey @Evolution0 thanks for contributing! I've been really busy this week so I haven't got the time to review this properly.

However, regarding inconsistent test data, you can make use of `requests-cache` which is already configured in `./nosetests.py`. In short, running `python3 nosetests.py` the first time on your local machine will make `requests-cache` cache all http responses to `./test_cache.sqlite`. Feel free to add its changes into version control. That way you'll aways have consistent seed page HTML to test with.

I'll get back to this next week when I have more free time to review for a merge.

**Comment by Evolution0** [comment]
I completely drew a blank on what those files even were, makes sense now. I was running nosetests in PyCharm by just right clicking the test folder and letting it run so no caching was being done 😮 ran it properly this time, fixed the urls one by one based on the errors nosetests threw back and all is good now.

Also learned something good out of this, I have another project I work on that does requests and I had no idea how to go about writing tests for it.

Take your time man, In the mean time I got other parsers to add 😉 

Edit: One improvement I can think of to add to this parser would be cleaning up of the authors fetching. Mangapanda likes to add illustrators to the authors row and add tags like (Art), (Story), (Story & Art). Seems I would need to do an initial pass and remove any names appended by an Art tag.. but limiting the scope is a bit hard as Mangapanda mixes "Last, First" and "First Last", both with or without tags so I can't simply match by the tag and stop at the ",". I may or may not look into some kind of helper function that gets the non-site specific info elsewhere. (Artist, illustrator, publisher, etc) If that sounds like a good idea.

**Comment by nhanb** [comment]
@Evolution0 I've finally found time to merge this. That worked great, thank you so much!

I took the liberty to squash your changes into one commit and also added a subsequent one (03f0fcfed1ae4284c23ca49e29045610d5723211) to clean some things up. The commit message is self-explanatory but let me elaborate on the generator refactor for `chapter.pages`: I return a generator instead of list in places where I potentially need to send multiple http requests (most obvious case being `chapter.pages` on sites that don't have "view all chapter at once" mode). The generator is supposed to yield every time it's fetched a new page so that any progam using this library will have real-time results to work with. Your implementation actually blocks the application flow until it's fetched all pages, which defeats the purpose.

About descending chapter list, that's intentional, and even if the source site does the opposite, the library should reverse it for consistency. This library is part of my ongoing effort to rewrite [my online manga reader](https://pytaku.appspot.com/series/http%3A%2F%2Fkissmanga.com%2FManga%2FMonster), which shows chapters in descending order.

Since I'm still figuring things out as I go, I left out development docs on purpose until I've got substantial work done. Artist vs Author is one of the things I'm still not sure how to approach, because as you already know, different sites provide different sets of data. Some don't event have the distinction between these two. I guess I'll find a good middleground once I've actually used this library for my new site.

**Comment by Evolution0** [comment]
Yeah there was still a bit of cleanup to do but didn't want the commit log to get too long.

As for netloc, weird, the kissmanga parser doesn't have www. in it.

Forgot about making pages a generator, makes sense though as you don't want to generate the whole thing at once every time.

**Pull request closed without merging**
